name: CI Pipeline

on:
  push:
    branches:
      - develop
      - release
      - master
  pull_request:
    branches:
      - develop
      - release
      - master

jobs:
  python:
    uses: ${{ values.owner }}/dvsp_workflows_python/.github/workflows/python.yml@master
    secrets: inherit
