//go:build !ignore_autogenerated

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *PlatformService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PlatformService) DeepCopy() *PlatformService {
	if in == nil {
		return nil
	}
	out := new(PlatformService)
	in.DeepCopyInto(out)
	return out
}

func (in *PlatformService) DeepCopyInto(out *PlatformService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PlatformServiceSpec) DeepCopyInto(out *PlatformServiceSpec) {
	*out = *in
	if in.InfraResources != nil {
		in, out := &in.InfraResources, &out.InfraResources
		*out = make([]InfraResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *InfraResource) DeepCopyInto(out *InfraResource) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *PlatformServiceStatus) DeepCopyInto(out *PlatformServiceStatus) {
	*out = *in
	if in.ProvisionedResources != nil {
		in, out := &in.ProvisionedResources, &out.ProvisionedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

func (in *PlatformServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PlatformServiceList) DeepCopy() *PlatformServiceList {
	if in == nil {
		return nil
	}
	out := new(PlatformServiceList)
	in.DeepCopyInto(out)
	return out
}

func (in *PlatformServiceList) DeepCopyInto(out *PlatformServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *InfraRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InfraRequest) DeepCopy() *InfraRequest {
	if in == nil {
		return nil
	}
	out := new(InfraRequest)
	in.DeepCopyInto(out)
	return out
}

func (in *InfraRequest) DeepCopyInto(out *InfraRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *InfraRequestSpec) DeepCopyInto(out *InfraRequestSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *InfraRequestStatus) DeepCopyInto(out *InfraRequestStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

func (in *InfraRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InfraRequestList) DeepCopy() *InfraRequestList {
	if in == nil {
		return nil
	}
	out := new(InfraRequestList)
	in.DeepCopyInto(out)
	return out
}

func (in *InfraRequestList) DeepCopyInto(out *InfraRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfraRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
